global:
  costcenter: "c1234"
  ApplicationName: "Jenkins"
  ApplicationId: "12345"
dev:
  https_port: 443
  db_user: "devDB_user"
  color: "green"
  instance_type: "t2.micro"
  instance_count: 1
qa:
  https_port: 8443
  db_user: "qaDB_user"
  color: "yello"
  instance_type: "t3.medium"
  instance_count: 2
prod:
  https_port: 443
  db_user: "qaDB_user"
  color: "red"
  instance_type: "m5.Xlarge"
  instance_count: 5