global:
  costcenter: "c1234"
  ApplicationName: "Jenkins"
  ApplicationId: "12345"
dev:
  https_port: 443
  db_user: "devDB_user"
  color: "red"
  instance_type: "t2.micro"
  instance_count: 1
qa:
  https_port: 443
  db_user: "dqaDB_user"
  color: "red"
  instance_type: "t2.micro"
  instance_count: 2